// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyrbneyxcxptnlvwijgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cmJuZXl4Y3hwdG5sdndpamdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTk2MzksImV4cCI6MjA3MDAzNTYzOX0.MjfBBUEaXcrnMpwO8QwEps9vzbxsoARPzylE9sPMaCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});